// [修正] src/app/layout.tsx

import type { Metadata } from "next";
// [修正] 將 Geist 字型替換為標準的 Inter 字型
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";

// [修正] 初始化 Inter 字型
// 我們保留了 variable 名稱 (--font-geist-sans) 以避免需要修改 CSS 檔案
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* [修正] 更新 body 的 className，暫時移除 mono 字型以簡化 */}
      <body
        className={`${inter.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}